### ISSUE TITLE
Pointer Tip of a page pointer cannot be hidden

### ISSUE THREAD

**Issue by Bit-Worker** [trevorsandy/lpub3d#813]
**Summary**

After placing a page pointer, I wanted to hide the tip (right-click on the pointer and select 'Edit Line Attributes', 'Hide Pointer Tip'). The line
'0 !LPUB PAGE POINTER_ATTRIBUTE LINE SOLID COLOR "Black" WIDTH 0.031 HIDE_TIP TRUE ID 1 BASE_RIGHT' is inserted, but the pointer tip remains visible.

**LPub3D Version**
 2.4.9 Revision 36 Build 4083 SHA 13948b6f5
Installation with LDraw's All-IN-One Installer
  
**Runtime Environment**

  - Operating system: Windows 10 Pro 264 bit (build 19045) in a virtul maschine (VirtualBox 7.0)
  - Hardware architecture:  x86-64
  - CPU model: AMD Ryzen 7 3700X
  - GPU model: VirtuallBox Graphics Adapter

**Steps to Reproduce**

1. Create an ldr file
2. Place a page pointer
3. Hide the pointer tip

**Expected Behavior**

The pointer tip should be invisible.

**Actual Behavior**
The pointer tip remains visible and the checkbox in the submenu is empty again.

**Output or example Input**<details>

![Image](https://github.com/user-attachments/assets/5e26a86e-1048-4eec-b720-a5f9c68f2374)

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour.

This behaviour has been corrected.

<details>

![Image](https://github.com/user-attachments/assets/45f6e1f3-ffe0-43c6-b82c-44f5f1ab2cd9)

</details>

Cheers,

**Comment by Bit-Worker** [comment]
Hi Trevor,

I have to open this topic again. I have downloaded the latest official version (2.49 build 4047) from 9.1.2025. I still have the problem.
What have I done.
I unzipped the ZIP file, started LPub3D.exe, selected LDView as the renderer.
Opened the example file car.ldr. Selected “Place Page Pointer, Right”.
Pointer appears with pointer tip, the following line is inserted:
0 !LPUB PAGE POINTER CENTER 0.0 0.49812 0.495495 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1 BASE_RIGHT
'Edit Line Attributes, Hide Pointer Tip'. The following line is added:
0 !LPUB PAGE POINTER_ATTRIBUTE LINE SOLID COLOR "Black" WIDTH 0.031 HIDE_TIP TRUE ID 1 BASE_RIGHT
But the pointer tip remains visible.

The same behaviour as described above.
